/sbin/tc qdisc del dev eno1 root
/sbin/tc qdisc del dev eno2 root
/sbin/tc qdisc del dev br0 root
/sbin/tc qdisc del dev br200 root
/sbin/tc qdisc del dev kvm501 root
/sbin/tc qdisc del dev kvm501 ingress
/sbin/tc qdisc del dev kvm501 root
/sbin/tc qdisc del dev kvm501 ingress
/sbin/tc qdisc del dev kvm501 root
/sbin/tc qdisc del dev kvm501 ingress
/sbin/tc qdisc del dev kvm501 root
/sbin/tc qdisc del dev kvm501 ingress
/sbin/tc qdisc del dev vnet25 root
/sbin/tc qdisc del dev vnet25 ingress
/sbin/tc qdisc del dev vnet25 root
/sbin/tc qdisc del dev vnet25 ingress
/sbin/tc qdisc del dev vnet27 root
/sbin/tc qdisc del dev vnet27 ingress
/sbin/tc qdisc del dev vnet24 root
/sbin/tc qdisc del dev vnet24 ingress